### ISSUE TITLE
Update LethalLib to 0.16.1

### ISSUE THREAD

**Issue by Jatc252** [Ccode-lang/LethalSirenHead#19]
The level type `Vanilla` in LethalLib must have been broken as it was recently fixed in [0.16.1](https://github.com/EvaisaDev/LethalLib/releases/tag/v0.16.1).

> Levels.LevelTypes.Vanilla now works for registering enemies and items on moons.

**Comment by Ccode-lang** [comment]
You should just be able to update it in the thunderstore profile and it should work.

**Comment by Jatc252** [comment]
Committed to #20
