### ISSUE TITLE
He can't kill me...

### ISSUE THREAD

**Issue by Paradox75831004** [Ccode-lang/LethalSirenHead#2]
I created EXP on the map, it came at me and couldn’t kill me in any way :c

![image](https://github.com/Ccode-lang/LethalSirenHead/assets/72872478/5e525211-35dd-49aa-ba17-9a3cfb1f8865)

The walking animation is nice, but he needs to make stages of aggression:
1. Noticed and walks slowly
2. Starts to speed up (siren howl)

**Comment by Paradox75831004** [comment]
You can hear the siren sounds (when he noticed you) when you enter the complex

**Comment by Ccode-lang** [comment]
The killing is fixed now.
